### ISSUE TITLE
.......

### ISSUE THREAD

**Issue by theratlesnake** [lovedboy/cracker#10]
...

**Comment by ls0f** [comment]
看 Read.me里面的Quick Test.

**Comment by theratlesnake** [comment]
我双击了local.exe ，然后再哪里输账号密码哦

**Comment by ls0f** [comment]
在cmd下面运行。

**Comment by theratlesnake** [comment]
可以运行啦，非常感谢博主。只是速度很慢，不过打开网页还是没问题的。想再请问下，如果自己在heroku上部署服务端，有教程吗？我之前在heroku上部署过其他的，一直都搞不定，太难了。

**Comment by ls0f** [comment]
Five hundred CNY or Google
