### ISSUE TITLE
Windows下如何实现编辑服务器地址

### ISSUE THREAD

**Issue by wangwill** [lovedboy/cracker#11]
感谢大佬！  已成功部署在自己的heroku application上并且在linux环境连成功。

windows环境下如何使用exe文件连上， 除了npm那种方式?

**Comment by ls0f** [comment]
下载exe文件，在cmd下面运行

**Comment by wangwill** [comment]
额。。求指点。。  
![image](https://cloud.githubusercontent.com/assets/9379983/25831652/c469cb9e-34a4-11e7-8955-9d0670fff118.png)

**Comment by ls0f** [comment]
windows_amd64_local.exe  -raddr https://lit-citadel-13724.herokuapp.com -secret 123456

**Comment by wangwill** [comment]
哦哦哦  好的   可以把read.me 添加下这行

**Comment by ls0f** [comment]
@wangwill 可否帮写个部署教程 https://github.com/lovedboy/cracker-heroku 很多人咨询怎么在heroku上部署.

**Comment by wangwill** [comment]
嗯？  这个很简单   需要放到你另一个repository的描述里么？

**Comment by ls0f** [comment]
对，就在这个 https://github.com/lovedboy/cracker-heroku 提交个PR就行，尽量做到图文并茂的step by step 😆

**Comment by wangwill** [comment]
(ˉ﹃ˉ) 嗯 没玩过github里的pr 我找找先。。
