### ISSUE TITLE
使用自签证书出错

### ISSUE THREAD

**Issue by ghost** [lovedboy/cracker#13]
错误如下： x509: certificate signed by unknown authority

都是按照readme中的实例操作的

**Comment by ls0f** [comment]
@lijyigithub 贴下server和local的运行命令.

**Comment by ghost** [comment]
`./linux_amd64_server -addr :443 -secret whatever -https -cert ./cert.pem -key ./key.pem`

`./linux_amd64_local -raddr https://myhost -secret whatever -cert ./cert.pem  -addr :1080`

**Comment by ls0f** [comment]
生成证书的时候输入的是域名还是ip，如果是ip，换成域名+绑定host试下。

**Comment by ls0f** [comment]
@lijyigithub 我用ip出现了这种情况。谢谢反馈。

**Comment by duhd1993** [comment]
最近各种“谣言”满天飞，repo主能不能介绍下这种协议的安全性怎么样啊？另外速度和tcp比一般怎么样呢？

**Comment by ls0f** [comment]
* 依赖TLS的安全性，具体可看https的实现。
* http[s]就是基于tcp的协议。

**Comment by ghost** [comment]
@ls0f 
重新生成证书测试了一下，可以使用，可能是我第一次生成证书的时候哪里搞错了。
非常不错的软件，作者辛苦了。
