### ISSUE TITLE
生成的证书只能自己使用么？

### ISSUE THREAD

**Issue by duhd1993** [lovedboy/cracker#15]
我在自己的MAC操作，安装到Heroku的，可以使用。但是在别的Windows电脑上使用就会报错，certificate signed by unknown authority，我把cert.pem复制了的，也提示load cert.pem success

**Comment by ls0f** [comment]
安装到heroku，是不需要证书的啊，heroku本身就支持https。
win下面和unix下面导入证书的机制不同，unix是append机制，win下面replace操作，所以win下面导入证书的话，就会不信任其他的证书签发机构。如果是heroku的话，win下面不要导入证书，除非是部署在自己的vps上面。

**Comment by duhd1993** [comment]
的确，我还以为我是在用自己签发的证书，哈哈....
另外还有个问题，刚在vps上装了，不过用IP生成的证书好像有问题，cannot validate certificate for *** because it doesn't contain any IP SANs 。Google了一下，用这个脚本生成的没有问题，请问要怎么使用openssl才行。https://raw.githubusercontent.com/driskell/log-courier/1.x/src/lc-tlscert/lc-tlscert.go

**Comment by ls0f** [comment]
用域名，然后绑定host

**Comment by duhd1993** [comment]
我知道用域名可以的，不过不做网站，懒得搞域名了。请问用IP有什么坏处么

**Comment by ls0f** [comment]
绑定host，没必要买域名啊==
