### ISSUE TITLE
下载最新版，用官方服务器运行错误

### ISSUE THREAD

**Issue by koolwiki** [lovedboy/cracker#9]
如题，下载的是最新windows版。运行参数：cracker -raddr https://lit-citadel-13724.herokuapp.com -secret 123456
浏览器里面选的是sock5代理。

17-04-23 12:46:05.074 INFO @socks5.go:85 socks5 proxy listen at:[127.0.0.1:1080]
17-04-23 12:46:05.074 INFO @http.go:66 http proxy listen at:[127.0.0.1:8080]
17-04-23 12:46:18.405 WARN @socks5.go:32 only support sock5...
17-04-23 12:46:26.407 WARN @socks5.go:32 only support sock5...
panic: runtime error: slice bounds out of range

goroutine 34 [running]:
panic(0x62ff60, 0xc042006050)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1af
github.com/lovedboy/cracker/cracker/http_connect.(*httpConnect).handleConn(0xc042093380, 0x774b20, 0xc0420fa008)
	/home/travis/gopath/src/github.com/lovedboy/cracker/cracker/http_connect/http.go:31 +0x7ec
created by github.com/lovedboy/cracker/cracker/http_connect.NewHttpConnect.func1
	/home/travis/gopath/src/github.com/lovedboy/cracker/cracker/http_connect/http.go:78 +0x98

**Comment by koolwiki** [comment]
后来在同一台电脑上运行server和local，发现都不行。
server命令：server -addr :1024 -secret 123456
local命令：local -raddr http://127.0.0.1:1024 -secret 123456

local运行后开始使用代理还是出现上面一样的错误。

**Comment by ls0f** [comment]
@hbxntsxw Thanks for feedback,i will handle it.

**Comment by ls0f** [comment]
@hbxntsxw 看上面的日志显示的你用的http代理？端口配置错了吗？ 我在win笔记本上没出现这个报错。

**Comment by koolwiki** [comment]
@lovedboy 谢谢你的回复！我浏览器里面配置端口是8080（127.0.0.1:8080）。配置成1080会没有反应，配置成8080后一开始通信，local端程序就会报错退出。

**Comment by ls0f** [comment]
协议选对了吗？8080 是http代理，1080是socks5代理。用的什么浏览器插件？

**Comment by koolwiki** [comment]
@lovedboy 那我选错了，我选的是sock5。我再试试！

**Comment by koolwiki** [comment]
@lovedboy 这次试了可以运行，谢谢！不过你的官方服务器是不是连不通啊？

**Comment by lovedboy** [comment]
你指的是 https://lit-citadel-13724.herokuapp.com 吗？我这边是可以的。

**Comment by ls0f** [comment]
@hbxntsxw 修复了http proxy的一些bug，下载
 最新版的local试下https://github.com/lovedboy/cracker/releases/tag/v2.2.1
最新版单个端口同时支持http和sock5协议。

**Comment by koolwiki** [comment]
@lovedboy 是指这个。我用这个试了http、http和sock5都无法连接。

**Comment by koolwiki** [comment]
@lovedboy 新版用你的服务器也连不上。浏览器上http、https和sock5代理服务器都配置成127.0.0.1:1080。

E:\>local -raddr https://lit-citadel-13724.herokuapp.com -secret 123456
17-04-24 13:41:47.036 INFO @local_proxy.go:49 socks5/http proxy listen at:[127.0.0.1:1080]
17-04-24 13:43:30.889 ERRO @socks5.go:41 proxy connect err:status code is 500, body is:404
17-04-24 13:43:32.941 ERRO @socks5.go:41 proxy connect err:status code is 500, body is:404
17-04-24 13:43:40.458 ERRO @socks5.go:41 proxy connect err:status code is 500, body is:404
17-04-24 13:43:51.942 ERRO @socks5.go:41 proxy connect err:status code is 500, body is:404
17-04-24 13:43:53.923 ERRO @socks5.go:41 proxy connect err:status code is 500, body is:404
17-04-24 13:43:55.448 ERRO @socks5.go:41 proxy connect err:status code is 500, body is:404
17-04-24 13:43:55.823 ERRO @http.go:44 proxy connect err:status code is 500, body is:404
17-04-24 13:43:57.938 ERRO @http.go:44 proxy connect err:status code is 500, body is:404
17-04-24 13:43:58.277 ERRO @local_proxy.go:25 read err:EOF
17-04-24 13:43:58.278 ERRO @local_proxy.go:25 read err:EOF
17-04-24 13:43:58.278 ERRO @local_proxy.go:25 read err:EOF
17-04-24 13:43:58.278 ERRO @local_proxy.go:25 read err:EOF
17-04-24 13:43:58.278 ERRO @local_proxy.go:25 read err:EOF
17-04-24 13:43:58.777 ERRO @http.go:44 proxy connect err:status code is 500, body is:404

**Comment by ls0f** [comment]
@hbxntsxw 有一个可能是你电脑的时间不对，如果时间不对，校正下时间试下。

**Comment by koolwiki** [comment]
@lovedboy 我下班后在自己的vps上安装一下试试。谢谢你的耐心回复！

**Comment by ls0f** [comment]
@hbxntsxw 在服务器上运行`./server -addr :8080 -secret <password> -debug` 可以开启debug选项看更详细的日志

**Comment by koolwiki** [comment]
@lovedboy 回家试了一下，可以连上你的服务器。我猜可能公司电脑没有管理员权限，打不开端口。这个软件是不是比shadowsocks更不容易被墙发现啊？

**Comment by ls0f** [comment]
@hbxntsxw 不是这个原因，应该是你公司电脑时间不对。

**Comment by koolwiki** [comment]
@lovedboy 搞不懂，时间是对的。不过也不纠结了，软件能用就好。
